"""Adding unique award keys to FSRS award tables

Revision ID: ffdb025c1eaf
Revises: 5f29b283f23e
Create Date: 2019-05-23 12:40:28.913394

"""

# revision identifiers, used by Alembic.
revision = 'ffdb025c1eaf'
down_revision = '5f29b283f23e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsrs_grant', sa.Column('unique_award_key', sa.String(), nullable=True))
    op.add_column('fsrs_procurement', sa.Column('unique_award_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data_broker():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fsrs_procurement', 'unique_award_key')
    op.drop_column('fsrs_grant', 'unique_award_key')
    # ### end Alembic commands ###

